dataset: Test_Time_Learning
sub_dataset: ag_news_real_oot
file_path: data/oot_generated/oot_gen_21.txt
name: oot_generated_21
format: text
seed: 56
max_test_samples: 0
split: test
description: 'Real AG News OOT dataset #21 (No Repetition)'
