dataset: Test_Time_Learning
sub_dataset: mixed_hard_oot
file_path: data/oot_generated/oot_gen_38.txt
name: oot_generated_38
format: text
seed: 105
max_test_samples: 0
split: test
description: 'Mixed Hard Negative OOT #38'
