dataset: Test_Time_Learning
sub_dataset: mixed_hard_oot
file_path: data/oot_generated/oot_gen_40.txt
name: oot_generated_40
format: text
seed: 107
max_test_samples: 0
split: test
description: 'Mixed Hard Negative OOT #40'
