dataset: Test_Time_Learning
sub_dataset: ag_news_real_oot
file_path: data/oot_generated/oot_gen_8.txt
name: oot_generated_8
format: text
seed: 43
max_test_samples: 0
split: test
description: 'Real AG News OOT dataset #8 (No Repetition)'
