dataset: Test_Time_Learning
sub_dataset: mixed_hard_oot
file_path: data/oot_generated/oot_gen_35.txt
name: oot_generated_35
format: text
seed: 102
max_test_samples: 0
split: test
description: 'Mixed Hard Negative OOT #35'
