dataset: Test_Time_Learning
sub_dataset: ag_news_real_oot
file_path: data/oot_generated/oot_gen_28.txt
name: oot_generated_28
format: text
seed: 63
max_test_samples: 0
split: test
description: 'Real AG News OOT dataset #28 (No Repetition)'
