dataset: Test_Time_Learning
sub_dataset: ag_news_real_oot
file_path: data/oot_generated/oot_gen_15.txt
name: oot_generated_15
format: text
seed: 50
max_test_samples: 0
split: test
description: 'Real AG News OOT dataset #15 (No Repetition)'
