dataset: Test_Time_Learning
sub_dataset: ag_news_real_oot
file_path: data/oot_generated/oot_gen_12.txt
name: oot_generated_12
format: text
seed: 47
max_test_samples: 0
split: test
description: 'Real AG News OOT dataset #12 (No Repetition)'
