dataset: Test_Time_Learning
sub_dataset: mixed_hard_oot
file_path: data/oot_generated/oot_gen_34.txt
name: oot_generated_34
format: text
seed: 101
max_test_samples: 0
split: test
description: 'Mixed Hard Negative OOT #34'
