dataset: Test_Time_Learning
sub_dataset: mixed_hard_oot
file_path: data/oot_generated/oot_gen_61.txt
name: oot_generated_61
format: text
seed: 128
max_test_samples: 0
split: test
description: 'Mixed Hard Negative OOT #61'
