agent_name: rag_bm25
model: Qwen/Qwen2.5-7B-Instruct
agent_type: rag
retrieve_num: 10
temperature: 0.7
max_tokens: 512
input_length_limit: 3000000000
buffer_length: 200
output_dir: ./outputs/glm-z1-9b
