agent_name: Embedding_rag_qwen3_embedding_4b
model: openai/gpt-4o-mini

#添加?将文本转换成向量
text_embedding: qwen/qwen3-embedding-8b

temperature: 0.7
input_length_limit: 10000000
buffer_length: 200
output_dir: ./outputs/gpt-4o-mini-qwen3_embedding_4b

retrieve_num: 1